# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [15]:
import numpy as np

original_array = np.random.randint(10, size=12)
print("original array :")
print(original_array)
reshaped_array = original_array.reshape(3, 4)
print("Reshaped array:")
print(reshaped_array)

# Concatenate two NumPy arrays horizontally
array1 = np.random.randint(10, size=(2, 2))
array2 = np.random.randint(10, size=(2, 2))
print("\narray1:")
print(array1)
print("array1:")
print(array1)
horizontal_concat = np.concatenate((array1, array2), axis=1)
print("\nHorizontally concatenated array:")
print(horizontal_concat)

# Concatenate two NumPy arrays vertically
array1 = np.random.randint(10, size=(2, 2))
array2 = np.random.randint(10, size=(2, 2))
print("\narray1:")
print(array1)
print("array1:")
print(array1)
vertical_concat = np.concatenate((array1, array2), axis=0)
print("\nVertically concatenated array:")
print(vertical_concat)

original array :
[5 4 2 8 6 2 7 5 5 4 2 5]
Reshaped array:
[[5 4 2 8]
 [6 2 7 5]
 [5 4 2 5]]

array1:
[[8 7]
 [5 0]]
array1:
[[8 7]
 [5 0]]

Horizontally concatenated array:
[[8 7 6 9]
 [5 0 1 4]]

array1:
[[5 7]
 [4 6]]
array1:
[[5 7]
 [4 6]]

Vertically concatenated array:
[[5 7]
 [4 6]
 [4 9]
 [1 5]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [16]:
import re

def classify_emails(emails):
  important_emails = []
  promotional_emails = []
  spam_emails = []

  for email in emails:
    if re.search(r"(important|urgent|priority)", email, re.IGNORECASE):
      important_emails.append(email)
    elif re.search(r"(sale|discount|offer|promotion)", email, re.IGNORECASE):
      promotional_emails.append(email)
    elif re.search(r"(viagra|casino|free money|click here)", email, re.IGNORECASE):
      spam_emails.append(email)
  return important_emails, promotional_emails, spam_emails

emails = ["Important: Meeting Agenda", "50% Off Sale!", "Get Rich Quick Scheme", "Urgent: Project Update", "Free iPhone!"]
important_emails, promotional_emails, spam_emails = classify_emails(emails)

print("Important emails:")
for email in important_emails:
  print(email)

print("\nPromotional emails:")
for email in promotional_emails:
  print(email)

print("\nSpam emails:")
for email in spam_emails:
  print(email)

Important emails:
Important: Meeting Agenda
Urgent: Project Update

Promotional emails:
50% Off Sale!

Spam emails:


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [17]:
#code here
# Create a dictionary of English words and their Spanish translations
english_spanish_dictionary = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "you're welcome": "de nada",
    "yes": "sí",
    "no": "no",
    "dog": "perro",
    "cat": "gato",
    "house": "casa",
    "car": "coche"
}

# Get the user's input
while True:
    english_word = input("Enter an English word (or type 'exit' to quit): ")

    # Check if the word exists in the dictionary
    if english_word in english_spanish_dictionary:
        # Print the Spanish translation
        spanish_translation = english_spanish_dictionary[english_word]
        print(f"The Spanish translation of '{english_word}' is '{spanish_translation}'.")
    elif english_word == 'exit':
        break
    else:
        # Inform the user that the translation is not available
        print(f"Sorry, the translation for '{english_word}' is not available in the dictionary.")

Enter an English word (or type 'exit' to quit): hello
The Spanish translation of 'hello' is 'hola'.
Enter an English word (or type 'exit' to quit): exit


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [18]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))


In [21]:
import pandas as pd
data = pd.read_csv("/content/vgsalesGlobale.csv")
data

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [33]:
total_global_sales = data['Global_Sales'].sum()

highest_selling_game = data[data['Global_Sales'] == data['Global_Sales'].max()]

average_sales_by_region =data[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean(axis=0)

top_5_genres = data.groupby('Genre').sum()['Global_Sales'].nlargest(5)

total_sales_by_genre_region = data.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_na = total_sales_by_genre_region.sort_values(by='NA_Sales', ascending=False).index[0]

last = data.tail(10)

top_3_platforms = data.groupby('Platform').sum()['Global_Sales'].nlargest(3)

market_share_by_genre = (data.groupby('Genre').sum()['Global_Sales'] / total_global_sales) * 100

correlation_na_eu = data[['NA_Sales', 'EU_Sales']].corr().iloc[0, 1]


print("Total global sales:", total_global_sales)
print("Game with highest global sales:")
print(highest_selling_game)
print("Average sales by region:")
print(average_sales_by_region)
print("Top 5 most popular game genres:")
print(top_5_genres)
print("Most popular genre in North America:", most_popular_genre_na)
print("Last 10 rows of the dataset:")
print(last)
print("Top 3 gaming platforms with highest global sales:")
print(top_3_platforms)
print("Market share by genre:")
print(market_share_by_genre)
print("Correlation coefficient between NA_Sales and EU_Sales: \n", correlation_na_eu)

Total global sales: 8920.44
Game with highest global sales:
   Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74  
Average sales by region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
Top 5 most popular game genres:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
Most popular genre in North America: Action
Last 10 rows of the dataset:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PS

<ipython-input-33-117243a6fe47>:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  top_5_genres = data.groupby('Genre').sum()['Global_Sales'].nlargest(5)
<ipython-input-33-117243a6fe47>:14: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  top_3_platforms = data.groupby('Platform').sum()['Global_Sales'].nlargest(3)
<ipython-input-33-117243a6fe47>:16: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  market_share_by_genre = (data.g